<#
.SYNOPSIS
    HTML to Word/PDF/Markdown converter (Windows)

.DESCRIPTION
    Convert HTML files generated by html-generator to Word (.docx), PDF (.pdf)
    or Markdown (.md).
    Auto-manages Python venv/conda, installs deps on first run (including Playwright Chromium).

.PARAMETER Format
    Output format: docx, pdf or md

.PARAMETER InputFile
    Input HTML file path (NOTE: named InputFile because $Input is a PowerShell automatic variable)

.PARAMETER OutputFile
    Output file path

.PARAMETER Yes
    Skip interactive confirmation when degradations are detected

.EXAMPLE
    .\convert.ps1 -Format docx -InputFile "report.html" -OutputFile "report.docx"
    .\convert.ps1 -Format pdf -InputFile "report.html" -OutputFile "report.pdf"
    .\convert.ps1 -Format md -InputFile "report.html" -OutputFile "report.md"
#>

param(
    [Parameter(Mandatory=$true)][ValidateSet("docx","pdf","md")][string]$Format,
    [Parameter(Mandatory=$true)][string]$InputFile,
    [Parameter(Mandatory=$true)][string]$OutputFile,
    [switch]$Yes
)

$ErrorActionPreference = "Continue"

# ===== 编码设置：确保 PowerShell 5.1 下 Python 输出中文不乱码 =====
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8
$env:PYTHONIOENCODING = "utf-8"

# $PSScriptRoot may be empty when invoked via & from another session
$ScriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.PSCommandPath }
if (-not $ScriptDir) { $ScriptDir = "." }
$ScriptsDir = Split-Path $ScriptDir  # parent: scripts/ directory

# ===== Environment detection =====
function Get-PythonCmd {
    $useVenv = $false

    # Prefer conda
    $condaPath = Get-Command conda -ErrorAction SilentlyContinue
    if ($condaPath) {
        Write-Host "[INFO] conda detected, using conda environment" -ForegroundColor Cyan
        $envName = "html-convert"
        # 注意：conda 的进度条/通知写到 stderr，PowerShell 5.1 下会混入 stdout 污染后续变量，
        # 因此这里把 stderr 重定向到 $null，且创建失败时用标志回退 venv 而非依赖变量清空。
        $condaEnvs = conda env list 2>$null
        if ($condaEnvs -notmatch $envName) {
            Write-Host "[INFO] First run, creating conda env $envName (~1min)..." -ForegroundColor Yellow
            conda create -n $envName python=3.11 -y 2>$null | Out-Null
            if ($LASTEXITCODE -ne 0) {
                Write-Host "[WARN] conda 环境创建失败（可能是镜像源/网络问题），回退到 venv..." -ForegroundColor Yellow
                $useVenv = $true
            }
        }
        if (-not $useVenv) {
            # Detect --no-banner support
            $condaRunArgs = "run -n $envName python"
            $condaBannerTest = conda run --no-banner -n $envName python -c "pass" 2>&1 | Out-Null
            if ($LASTEXITCODE -eq 0) {
                $condaRunArgs = "run --no-banner -n $envName python"
            }
            # Check and install deps
            $depCheck = conda $condaRunArgs.Split() -c "import bs4, docx, lxml" 2>$null
            if ($LASTEXITCODE -ne 0) {
                Write-Host "[INFO] First run, installing dependencies..." -ForegroundColor Yellow
                $reqPath = Join-Path $ScriptsDir "requirements.txt"
                conda $condaRunArgs.Split() -m pip install -r $reqPath --quiet 2>$null | Out-Null
            }
            # docx/pdf 格式：检查 Playwright（docx 图表卡截图、pdf 渲染均需要）
            if ($Format -in @("docx", "pdf")) {
                $pwCheck = conda $condaRunArgs.Split() -c "import playwright" 2>$null
                if ($LASTEXITCODE -ne 0) {
                    Write-Host "[INFO] Installing Playwright (includes Chromium, ~100MB)..." -ForegroundColor Yellow
                    conda $condaRunArgs.Split() -m pip install playwright --quiet 2>$null | Out-Null
                    $condaPlaywrightCmd = $condaRunArgs -replace " python$", " -m playwright"
                    conda $condaPlaywrightCmd.Split() install chromium 2>$null | Out-Null
                }
            }
            Write-Host "[INFO] conda environment ready" -ForegroundColor Green
            return "conda $condaRunArgs"
        }
    }

    # Fallback to venv (use absolute python.exe path directly, no reliance on activation)
    if (-not $useVenv) { Write-Host "[INFO] Using venv environment" -ForegroundColor Cyan }
    $envPath = Join-Path $env:USERPROFILE ".html-convert-env"
    $venvPython = Join-Path $envPath "Scripts\python.exe"
    if (-not (Test-Path $venvPython)) {
        Write-Host "[INFO] First run, creating venv and installing deps (~1min)..." -ForegroundColor Yellow
        python -m venv $envPath | Out-Null
        if ($LASTEXITCODE -ne 0) {
            Write-Host "[ERROR] Failed to create venv, please ensure Python 3.11+ is installed" -ForegroundColor Red
            exit 1
        }
        $reqPath = Join-Path $ScriptsDir "requirements.txt"
        & $venvPython -m pip install -r $reqPath --quiet | Out-Null
        if ($LASTEXITCODE -ne 0) {
            Write-Host "[ERROR] Failed to install dependencies" -ForegroundColor Red
            exit 1
        }
        # docx/pdf 格式：安装 Playwright
        if ($Format -in @("docx", "pdf")) {
            Write-Host "[INFO] Installing Playwright (includes Chromium, ~100MB)..." -ForegroundColor Yellow
            & $venvPython -m pip install playwright --quiet | Out-Null
            if ($LASTEXITCODE -ne 0) {
                Write-Host "[ERROR] Failed to install Playwright" -ForegroundColor Red
                exit 1
            }
            & $venvPython -m playwright install chromium
            if ($LASTEXITCODE -ne 0) {
                Write-Host "[ERROR] Failed to install Playwright Chromium" -ForegroundColor Red
                exit 1
            }
        }
        Write-Host "[INFO] Environment ready" -ForegroundColor Green
    } else {
        # venv 已存在：检查依赖是否齐全（缺则补装）
        & $venvPython -c "import bs4, docx, lxml" | Out-Null
        if ($LASTEXITCODE -ne 0) {
            Write-Host "[INFO] Dependencies missing, installing..." -ForegroundColor Yellow
            $reqPath = Join-Path $ScriptsDir "requirements.txt"
            & $venvPython -m pip install -r $reqPath --quiet | Out-Null
            if ($LASTEXITCODE -ne 0) {
                Write-Host "[ERROR] Failed to install dependencies" -ForegroundColor Red
                exit 1
            }
        }
        # docx/pdf 格式：检查 Playwright
        if ($Format -in @("docx", "pdf")) {
            & $venvPython -c "import playwright" | Out-Null
            if ($LASTEXITCODE -ne 0) {
                Write-Host "[INFO] Installing Playwright (includes Chromium, ~100MB)..." -ForegroundColor Yellow
                & $venvPython -m pip install playwright --quiet | Out-Null
                if ($LASTEXITCODE -ne 0) {
                    Write-Host "[ERROR] Failed to install Playwright" -ForegroundColor Red
                    exit 1
                }
                & $venvPython -m playwright install chromium | Out-Null
                if ($LASTEXITCODE -ne 0) {
                    Write-Host "[ERROR] Failed to install Playwright Chromium" -ForegroundColor Red
                    exit 1
                }
            }
        }
    }
    return $venvPython
}

# ===== Check input file =====
if (-not (Test-Path $InputFile)) {
    Write-Host "[ERROR] Input file not found: $InputFile" -ForegroundColor Red
    exit 1
}

# ===== Prepare environment =====
$pythonCmd = Get-PythonCmd

# ===== Helper: run Python script (compatible with conda run and direct python) =====
function Run-PythonScript {
    param([string]$ScriptPath, [string[]]$ScriptArgs)
    if ($pythonCmd -like "conda*") {
        # conda 分支：数组参数直接调用，避免 Invoke-Expression 字符串拼接被 PowerShell 误解析
        # $pythonCmd 形如 "conda run --no-banner -n html-convert python"（condaParts[0] 即 "conda"）
        $condaParts = $pythonCmd -split '\s+'
        & conda $condaParts[1..($condaParts.Length - 1)] $ScriptPath @ScriptArgs
    } else {
        # venv absolute python path
        & $pythonCmd $ScriptPath @ScriptArgs
    }
}

# ===== Markdown: 结构保真，视觉天然不保留，直接转换（跳过影响分析确认） =====
# 说明：Markdown 只保留结构（标题/列表/表格/代码块），视觉样式天然不保留属预期行为。
# 结构降级（卡片→列表、时间线→有序列表等）由 Agent 场景中的 LLM 在转换前做精简版
# 影响分析并询问用户；入口脚本不重复交互确认，直接执行转换。
if ($Format -eq "md") {
    Write-Host "[INFO] Markdown 转换为结构保真，直接执行..." -ForegroundColor Cyan
    Run-PythonScript (Join-Path $ScriptsDir "html2md.py") @($InputFile, $OutputFile)
    if ($LASTEXITCODE -eq 0) {
        Write-Host "[OK] Conversion complete: $OutputFile" -ForegroundColor Green
    } else {
        Write-Host "[ERROR] Conversion failed" -ForegroundColor Red
        exit 1
    }
    exit 0
}

# ===== Pre-conversion impact analysis (docx/pdf only) =====
# 只运行一次 --json 模式（人类可读模式由 LLM 负责呈现，脚本内不再重复运行）
Write-Host "[INFO] Analyzing conversion impact..." -ForegroundColor Cyan

$jsonResult = Run-PythonScript (Join-Path $ScriptsDir "impact_analyzer.py") @($InputFile, "--format", $Format, "--json")
$impactExit = $LASTEXITCODE

$needRemind = $false
if ($jsonResult) {
    try {
        $parsed = $jsonResult | ConvertFrom-Json
        $needRemind = $parsed.need_remind
    } catch {
        # JSON 解析失败：以退出码为准（need_remind=true 时退出码为 1）
        $needRemind = $impactExit -ne 0
    }
} else {
    $needRemind = $impactExit -ne 0
}

# 展示降级清单（human-readable 摘要，供用户确认时参考）
if ($needRemind -and $jsonResult) {
    try {
        $parsed = $jsonResult | ConvertFrom-Json
        if ($parsed.items -and $parsed.items.Count -gt 0) {
            Write-Host "[REMINDER] Conversion degradations detected:" -ForegroundColor Yellow
            foreach ($item in $parsed.items) {
                Write-Host "  - $item" -ForegroundColor Yellow
            }
        }
    } catch {
        # JSON 解析失败不阻塞流程
    }
}

if ($needRemind -and -not $Yes) {
    Write-Host "[REMINDER] Conversion degradations detected (see above), continue?" -ForegroundColor Yellow
    Write-Host "Press Y to continue, N to cancel" -ForegroundColor Yellow
    $confirm = Read-Host "Confirm (Y/N)"
    if ($confirm -ne "Y" -and $confirm -ne "y") {
        Write-Host "[INFO] Conversion cancelled" -ForegroundColor Cyan
        exit 0
    }
} elseif ($needRemind -and $Yes) {
    Write-Host "[INFO] Degradations detected, -Yes passed, skipping confirmation" -ForegroundColor Cyan
}

# ===== Execute conversion =====
Write-Host "[INFO] Converting: $InputFile -> $OutputFile ($Format)" -ForegroundColor Cyan

if ($Format -eq "docx") {
    Run-PythonScript (Join-Path $ScriptsDir "html2docx.py") @($InputFile, $OutputFile)
} elseif ($Format -eq "pdf") {
    Run-PythonScript (Join-Path $ScriptsDir "html2pdf.py") @($InputFile, $OutputFile)
}

if ($LASTEXITCODE -eq 0) {
    Write-Host "[OK] Conversion complete: $OutputFile" -ForegroundColor Green
} else {
    Write-Host "[ERROR] Conversion failed" -ForegroundColor Red
    exit 1
}

# ===== 转换完成 =====